### ISSUE TITLE
Function runApp 

### ISSUE THREAD

**Issue by alamata** [Spikharpax/Avatar-Serveur-3.0#2]
Bonjour à toi,..

Après un long moment  d'absence  et une mise à jour  serveur (3.3)   et client (web speech api v 1.1) , il ne m'est plus possible d'utiliser  la function  runApp.  

Qu'en es t il..?

rem: j'arrive  a  bypasser  cette  limitation,...mais  ca  reste moins pratique et plus lourd

**Comment by Spikharpax** [comment]
Bjr,

Je sais pas trop, cette fonction marche normalement. Enfin... si tu ne prends pas un dev de la version 1... C'est sûr que ca a peut être changé depuis. La documentation de développement est à jour normalement. Tu as regardé ?

Sinon, copie ton code que je vois comment tu fais pour passer ta commande à exécuter et où se trouve ton exécutable sur le client

**Comment by alamata** [comment]
Tout  d'abord, merci  pour l’intérêt  que  tu porte  à mon  soucis... ;))

Celui-ci  est assez simple, précédemment  par  exemple  cette instruction  donnait  le résultat  escompté : 

`Avatar.runApp('C:\\WINDOWS\\system32\\WindowsPowerShell\\v1.0\\powershell.exe',"-windowstyle hidden start-process  -FilePath 'C:\\Avatar3.3\\Client\\resources\\app\\mplayer\\mplayer.exe'  -windowstyle minimized  -ArgumentList "+'"'+ url +'","'+"-volume"+'","55"', room)`

ce n'est plus  le  cas,...

rem :  le  client   et le  serveur  se  trouvent  sur  la même machine (winn10 64 1909) et   c'est  une   fresh  install   du  serveur  3.3  et  du client ...


merci  de jeter un  coup  d’œil... )))

**Comment by Spikharpax** [comment]
La commande exacte:
Avatar.runApp('C:\\WINDOWS\\system32\\WindowsPowerShell\\v1.0\\powershell.exe start-process -windowstyle hidden -FilePath "C:/Avatar3.3/Client/resources/app/mplayer/mplayer.exe \'-volume 55 '+url+'\'"', null, room);

Ce que tu as écris ne peut pas marcher et franchement, je ne vois pas comment ca pouvait fonctionner avant, vraiment très bizarre, bref, ok.
Testé avec un fichier en local, ca fonctionne correctement, je n'ai pas testé avec une url mais ca doit être pareil puisque ce n'est qu'un argument de mplayer.

Néanmoins, il y a une particularité du fait que tu utilises un shell pour exécuter mplayer. Le shell est exécuté et retourne directement sans attendre la fin de l'exécution de mplayer (et du fichier son). 
Normal, mais le truc c'est que si jamais tu libères le client ensuite par un end(), le client risque de ne pas se libérer et tu ne pourras plus dialoguer avec. 
En parlant de ça, je ne vois pas de libération du client par un end() dans ta copie d'écran mais bon, peut être que tu le fais quelque part ou que tu exécutes cette fonction par un trigger sinon le mieux est de le libérer avant ton runapp comme ceci :

Avatar.Speech.end(room, null, function() {
Avatar.runApp('C:\\WINDOWS\\system32\\WindowsPowerShell\\v1.0\\powershell.exe start-process -windowstyle hidden -FilePath "C:/Avatar3.3/Client/resources/app/mplayer/mplayer.exe \'-volume 55 '+url+'\'"', null, room);
});
