### ISSUE TITLE
Avatar client

### ISSUE THREAD

**Issue by nezumi-neko** [Spikharpax/Avatar-Serveur-3.0#3]
Bonjour,

Je rencontre un problème avec le client web API qui ne trouve pas le serveur.
Je lance le serveur et voila ce que j'ai dans la console il affiche bien le port 3000.
Pourtant quand je lance le client web API il m'indique.
No avatar serveur in the network. new test in 15 sec... et ainsi de suite.
Il sont lancé sur le même PC et j'ai même élargit la plage de recherche au max (192.168.0.1-255) mais c'est pareil.

Pourriez vous me dire si j'ai oublié quelque chose?

David

**Comment by Spikharpax** [comment]
bonjour,

Vérifie en 1er l'ip de ton pc (ipconfig /all), ca doit donc commencer par 192.168.0 
Ensuite tu peux l'ajouter directement dans le fichier de configuration dans _**AvatarClient**\resources\app\Avatar.config_

"http": {
    "server": {
      "ip": "**XXX.XXX.XXX.XXX**",
      "port": 3000
    },

Il faut aussi que tu acceptes les accès aux ports quand il te le demande à l'ouverture du client et du serveur la 1ere fois.
Je me demande si un anti-virus peut aussi poser des problèmes... bien que j'ai Norton et ca passe sans problème.
Autre chose, ce n'est pas trop indiqué de mettre un plage de recherche aussi grande.
Par exemple si ton ip est 192.168.0.10 (ip fixe), tu peux mettre directement 192.168.0.10 dans _UDP-target_ ou si tu veux qu'il recherche, tu mets une plage genre 192.168.0.8-14
"UDP": {
    "port": 2222,
    "target": "**192.168.0.8-14**",

**OU**

"UDP": {
    "port": 2222,
    "target": "192.168.0.10",

Dernière chose, ce client quelque fois ne restitue pas l'écoute. Heureusement pas souvent mais ca peut arriver surtout si la bande passante du réseau est faible. 
Donc si tu n'arrives plus à déclencher l'écoute par le mot clé déclencheur alors tu peux sur le serveur cliquer sur le node du client et dans le menu contextuel, cliquer sur "**_Active l'écoute_**" ou alors dire directement **_"redémarre l'écoute"_**.
Je dois vérifier pourquoi il fait ca et le corriger. On verra en septembre...

Bon courage et tiens moi au courant.

**Comment by nezumi-neko** [comment]
Bonjour,

Merci beaucoup pour ton aide.
Pour l'antivirus, j'ai avast et il n'y a pas de problème non plus. 
Mon problème était bien mon adresse IP, je suis en 168.1692.1.79 et non en 192.168.0.xx. Je n'y avait même pas pensez lol.
J'ai réduit la plage comme tu l'as indiqué. 
Cela fonctionne bien du coup chez moi.
Pourrais avoir ton mail stp, j'aurai quelques autres questions à te poser concernant les plugins.
Voici le mien : nezumi.neko@hotmail.fr
Merci pour ton programme.
