### ISSUE TITLE
Version Linux ou Rasoberry du serveur

### ISSUE THREAD

**Issue by JarvisJKKA** [Spikharpax/Avatar-Serveur-3.0#5]
Bonjour,

Tout d'abbord, bravo pour ce boulot et ce projet.
J'ai forké pour regarder un peu le code et bidouiller. 
J'ai quelques petites questions.
Je suis surpris  de voir que la plateforme de base du serveur est sous Windows. Je n'ai rien contre Microsoft, au contraire, simplement je me demandais pourquoi pas une version linux (Debian Based type Ubuntu ou autre par exemple), surtout si c'est développé en Node et JS (Typescript, je n'ai pas regardé) ? 
De même, peut être que ce serveur pourrait fonctionner sous Raspberry Pi OS (Deian based d'ailleurs), tout comme les clients (J'ai vu que vous aviez fait un cleint Android). Idem si c'est sous Electron, ça ne devrait pas poser de problème. 
Est par choix ? Parce que vous utilisez des fonctions natives pas ou diffcillement portables ?  Parce que vous n'avez juste jamais essayé ? 
En tout cas, ce type de projet pourrait  parfaitement être relié à un projet de type Magic Mirror 2 sous Raspberry.
Ceci étant dit, encore bravo.

Bien à vous

**Comment by Spikharpax** [comment]
Version Windows par choix. 
Aujourd'hui il y a des petits pc en 5v au même prix qu'un PI donc Linux n'offre que très peu d’intérêt.
Par contre rien n'interdit de faire une version sous ce système. C'est faisable. Perso, je ne le ferais pas. J'ai assez à m'occuper avec une seule version.
Un bon codeur pourra le faire sans problème. Il y a juste un module en langage C qu'il faut recompiler et quelques petites choses au niveau du code. Rien de bien extraordinaire.

Pour un miroir magic, ca ne pose aucun problème de le faire avec un client Linux si on en a envie. J'ai fait un client sous Android donc... :-)

A+
